integrations:
  rss:
    enabled: true
    sources:
      - url: "https://www.reddit.com/r/kubernetes/new/.rss"
        since: 1h
        matchTitle:
          contains:
            - "CVE"
  gitlab:
    enabled: true
    baseURL: https://gitlab.com
    token: xxx
    listen:
      areas:
        - type: "PR"
      groups:
        - 111
        - 222
        - 333
alerts:
  slack:
    enabled: true
    webhook: "webhook"
    channel: "#channel"
    username: "Username"
    icon: ":icon:"